project_name: smug

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    gcflags:
      - "all=-trimpath={{.Env.GOPATH}}"
    ldflags:
     - "-X=main.version={{.Env.VERSION}}"
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - test
      - README
