on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  update-formulae:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          formula: smug
          force: true
          livecheck: false
